# Generated by Django 3.2.11 on 2022-04-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='name',
            field=models.CharField(default='Rental', max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
