# Generated by Django 3.2.11 on 2022-04-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='previous_reservation',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='name',
            field=models.CharField(default='Rental', max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
