# Generated by Django 3.2.11 on 2022-04-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220405_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='previous_reservation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
