# Generated by Django 3.2.11 on 2022-04-06 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_reservation_previous_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='previous_reservation',
        ),
    ]
